adding seven segment using decoder impelementation
AbdelrahmanBadr22/G1_8bit_MCUs_Drivers pull request #12
Opened 2023-07-28 18:41 UTC by noran97

2023-07-28 18:44 UTC, AbdelrahmanBadr22 commented
Hi @noran97 ,
Based on the new changes, it looks like this PR has a conflict issue. Could you please resolve it and let me know?

2023-07-28 19:04 UTC, AbdelrahmanBadr22 requested changes

2023-07-28 19:04 UTC, AbdelrahmanBadr22 commented on C/SEGMENT_DECODER.c
> +error_t SEGMENT_DECODER_INIT(SEGMENT_DECODER * seven_segment)
For pointers we use `p` so in this case we can use `pSevenSeg`

2023-07-28 19:04 UTC, AbdelrahmanBadr22 commented on C/SEGMENT_DECODER.c
> +        GPIO_SetPinDirection(seven_segment->segment[3].port_name,seven_segment->segment[3].pin_name,kOutput);
What about using for loop : 
e.g. 
```
for (i = 0 ; i < TOTAL_DECODER_PINS ; i++) {
    GPIO_SetPinDirection(seven_segment->segment[i].portNumber,seven_segment->segment[i].pinNumber,kOutput);
}
```

2023-07-28 19:04 UTC, AbdelrahmanBadr22 commented on C/SEGMENT_DECODER.h
> +#ifndef LCD_H_
Use correct macro name

2023-07-29 11:01 UTC, AbdelrahmanBadr22 requested changes

2023-07-29 11:01 UTC, AbdelrahmanBadr22 commented on C/SEVEN_SEGMENT.c
> +    int i=0;
Don't use `int`

2023-07-29 15:49 UTC, noran97 commented
@AbdelrahmanBadr22 
Can you please kindly review my code 💐

2023-08-08 18:58 UTC, AbdelrahmanBadr22 commented
Hi @noran97 ,
There are a tricky bug with your code, remember if you didn't the new directory to the `build.dir` then the directory won't be built then any compiler errors in the new directory won't be detected and one can use this files. In the future we will automate detecting new directory and avoid using `build.dir` but for now you have to add the new directories to the `build.dir`

2023-08-08 19:01 UTC, AbdelrahmanBadr22 requested changes

2023-08-09 17:30 UTC, closed without merging